### ISSUE TITLE
nodes for fologorycoin

### ISSUE THREAD

**Issue by goodthebest** [folgort/folgorycoin#4]
I've installed FLG wallet but not syncing blockchain still at 0. Could you please provide some addnodes ?

**Comment by prohub1** [comment]
Hi,
Come to telegram group of folgorycoin

Op wo 21 apr. 2021 om 21:24 schreef Linux server management, OS softwares
and applications, blockchain Mining Pools, Daemons ***@***.***

**Comment by prohub1** [comment]
Peers - FolgoryCoin
addnode=167.99.41.99:35084
addnode=185.154.12.89:27188
addnode=188.35.131.171:61547
addnode=45.138.72.107:35164
addnode=46.101.100.94:27188
addnode=46.150.169.54:27188
addnode=86.15.113.175:27188
addnode=86.57.193.186:27188
addnode=89.221.223.93:41862
